namespace ObsWebSocket.Net.Enums.Obs;

public enum ObsBoundsType : byte
{
    OBS_BOUNDS_NONE,
    OBS_BOUNDS_STRETCH,
    OBS_BOUNDS_SCALE_INNER,
    OBS_BOUNDS_SCALE_OUTER,
    OBS_BOUNDS_SCALE_TO_WIDTH,
    OBS_BOUNDS_SCALE_TO_HEIGHT,
    OBS_BOUNDS_MAX_ONLY
}